# Generated by Django 5.1.6 on 2025-03-09 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Guard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")],
                        default="male",
                        max_length=10,
                    ),
                ),
                (
                    "identification_document",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{1,11}$",
                                "Identification number must contain only digits and be up to 11 digits long.",
                            )
                        ],
                    ),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "cellphone_number",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{1,15}$",
                                "Phone number must contain only digits and be up to 10 digits long.",
                            )
                        ],
                    ),
                ),
                (
                    "village_assigned",
                    models.CharField(
                        choices=[
                            ("anabeb", "Anabeb"),
                            ("otjondunda", "Otjondunda"),
                            ("ombaikiha", "Ombaikiha"),
                            ("warmquelle", "Warmquelle"),
                            ("khowarib", "Khowarib"),
                            ("omukutu", "Omukutu"),
                            ("otjondumbu", "Otjondumbu"),
                            ("okaturua", "Okaturua"),
                            ("otjatjondjira", "Otjatjondjira"),
                        ],
                        default="warmquelle",
                        max_length=50,
                    ),
                ),
                ("date_employed", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="alive",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")],
                        default="male",
                        max_length=10,
                    ),
                ),
                (
                    "identification_document",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{1,11}$",
                                "Identification number must contain only digits and be up to 11 digits long.",
                            )
                        ],
                    ),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "cellphone_number",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{1,10}$",
                                "Phone number must contain only digits and be up to 10 digits long.",
                            )
                        ],
                    ),
                ),
                (
                    "village",
                    models.CharField(
                        choices=[
                            ("anabeb", "Anabeb"),
                            ("otjondunda", "Otjondunda"),
                            ("ombaikiha", "Ombaikiha"),
                            ("warmquelle", "Warmquelle"),
                            ("khowarib", "Khowarib"),
                            ("omukutu", "Omukutu"),
                            ("otjondumbu", "Otjondumbu"),
                            ("okaturua", "Okaturua"),
                            ("otjatjondjira", "Otjatjondjira"),
                        ],
                        default="warmquelle",
                        max_length=50,
                    ),
                ),
                ("date_join", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("alive", "Alive"), ("deceased", "Deceased")],
                        default="alive",
                        max_length=10,
                    ),
                ),
                ("date_deceased", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
