# Generated by Django 5.1.6 on 2025-04-05 12:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Anabeb Conservancy', max_length=255)),
                ('postal_address', models.CharField(default='P.O Box 108, Opuwo, Namibia', max_length=255)),
                ('address', models.CharField(default='Warmquelle, Kunene Region, Namibia', max_length=255)),
                ('phone', models.CharField(default='+264 81 123 4567', max_length=20)),
                ('email', models.EmailField(default='info@anabebconservancy.com', max_length=254)),
                ('website', models.URLField(default='http://anabebconservancy.com')),
                ('vat_number', models.CharField(default='1234567890', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/logos/')),
                ('stamp', models.ImageField(blank=True, null=True, upload_to='company/stamps/')),
            ],
        ),
        migrations.CreateModel(
            name='Guard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
                ('identification_document', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{1,11}$', 'Identification number must contain only digits and be up to 11 digits long.')])),
                ('date_of_birth', models.DateField()),
                ('cellphone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{1,15}$', 'Phone number must contain only digits and be up to 10 digits long.')])),
                ('village_assigned', models.CharField(choices=[('anabeb', 'Anabeb'), ('otjondunda', 'Otjondunda'), ('ombaikiha', 'Ombaikiha'), ('warmquelle', 'Warmquelle'), ('khowarib', 'Khowarib'), ('omukutu', 'Omukutu'), ('otjondumbu', 'Otjondumbu'), ('okaturua', 'Okaturua'), ('otjatjondjira', 'Otjatjondjira')], default='warmquelle', max_length=50)),
                ('date_employed', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='alive', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Enter the member's first name.", max_length=150)),
                ('last_name', models.CharField(help_text="Enter the member's last name.", max_length=150)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', help_text="Select the member's gender.", max_length=10)),
                ('identification_document', models.CharField(help_text="Enter the member's identification number (up to 11 digits).", max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,11}$', 'Identification number must contain only digits and be up to 11 digits long.')])),
                ('date_of_birth', models.DateField(help_text="Enter the member's date of birth.")),
                ('cellphone_number', models.CharField(help_text="Enter the member's cellphone number (up to 10 digits).", max_length=15, validators=[django.core.validators.RegexValidator('^\\d{1,10}$', 'Phone number must contain only digits and be up to 10 digits long.')])),
                ('village', models.CharField(choices=[('anabeb', 'Anabeb'), ('otjondunda', 'Otjondunda'), ('ombaikiha', 'Ombaikiha'), ('warmquelle', 'Warmquelle'), ('khowarib', 'Khowarib'), ('omukutu', 'Omukutu'), ('otjondumbu', 'Otjondumbu'), ('okaturua', 'Okaturua'), ('otjatjondjira', 'Otjatjondjira')], default='warmquelle', help_text="Select the member's village.", max_length=50)),
                ('date_join', models.DateField(help_text='Enter the date the member joined.')),
                ('status', models.CharField(choices=[('alive', 'Alive'), ('deceased', 'Deceased')], default='alive', help_text="Select the member's status.", max_length=10)),
                ('date_deceased', models.DateField(blank=True, help_text='Enter the date the member passed away (if applicable).', null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('identification_document',), name='unique_identification_document')],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, help_text='Base monthly salary before any deductions or bonuses.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('hours_worked', models.PositiveIntegerField(default=160, help_text='Total hours worked in the month. Default is 160 (full-time).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('overtime_hours', models.PositiveIntegerField(default=0, help_text='Extra hours worked beyond the normal working hours.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0.0, editable=False, help_text='Automatically calculated based on overtime hours and rate.', max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0.0, help_text='Additional earnings (performance bonus, holiday bonus, etc.).', max_digits=10)),
                ('allowances', models.DecimalField(decimal_places=2, default=0.0, help_text='Extra allowances (e.g., transport, housing).', max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0.0, help_text='Deductions (e.g., loans, penalties, or other reductions).', max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, editable=False, help_text='Automatically calculated 15% tax on basic salary.', max_digits=10)),
                ('net_pay', models.DecimalField(decimal_places=2, editable=False, help_text='Final salary after tax and deductions.', max_digits=10)),
                ('month', models.CharField(help_text="Month and year (e.g., 'April 2025').", max_length=20)),
                ('date_issued', models.DateField(auto_now_add=True, help_text='Date when the payslip was generated.')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='portal.companyinfo')),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='portal.guard')),
            ],
            options={
                'ordering': ['-date_issued'],
                'unique_together': {('guard', 'month')},
            },
        ),
    ]
