# Generated by Django 5.1.6 on 2025-03-10 20:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="cellphone_number",
            field=models.CharField(
                help_text="Enter the member's cellphone number (up to 10 digits).",
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{1,10}$",
                        "Phone number must contain only digits and be up to 10 digits long.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="date_deceased",
            field=models.DateField(
                blank=True,
                help_text="Enter the date the member passed away (if applicable).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="date_join",
            field=models.DateField(help_text="Enter the date the member joined."),
        ),
        migrations.AlterField(
            model_name="member",
            name="date_of_birth",
            field=models.DateField(help_text="Enter the member's date of birth."),
        ),
        migrations.AlterField(
            model_name="member",
            name="first_name",
            field=models.CharField(
                help_text="Enter the member's first name.", max_length=150
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="male",
                help_text="Select the member's gender.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="identification_document",
            field=models.CharField(
                help_text="Enter the member's identification number (up to 11 digits).",
                max_length=15,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{1,11}$",
                        "Identification number must contain only digits and be up to 11 digits long.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="last_name",
            field=models.CharField(
                help_text="Enter the member's last name.", max_length=150
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="status",
            field=models.CharField(
                choices=[("alive", "Alive"), ("deceased", "Deceased")],
                default="alive",
                help_text="Select the member's status.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="village",
            field=models.CharField(
                choices=[
                    ("anabeb", "Anabeb"),
                    ("otjondunda", "Otjondunda"),
                    ("ombaikiha", "Ombaikiha"),
                    ("warmquelle", "Warmquelle"),
                    ("khowarib", "Khowarib"),
                    ("omukutu", "Omukutu"),
                    ("otjondumbu", "Otjondumbu"),
                    ("okaturua", "Okaturua"),
                    ("otjatjondjira", "Otjatjondjira"),
                ],
                default="warmquelle",
                help_text="Select the member's village.",
                max_length=50,
            ),
        ),
        migrations.AddConstraint(
            model_name="member",
            constraint=models.UniqueConstraint(
                fields=("identification_document",),
                name="unique_identification_document",
            ),
        ),
    ]
