# Generated by Django 5.1.6 on 2025-04-05 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payslip',
            unique_together={('guard',)},
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='month',
        ),
    ]
