# Generated by Django 5.1.6 on 2025-04-07 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_payslip_unique_together_remove_payslip_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='portal.companyinfo'),
        ),
    ]
