# Generated by Django 5.1.6 on 2025-03-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_remove_guard_home_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guard",
            name="village_assigned",
            field=models.CharField(
                choices=[
                    ("anabeb", "Anabeb"),
                    ("otjondunda", "Otjondunda"),
                    ("ombaikiha", "Ombaikiha"),
                    ("warmquelle", "Warmquelle"),
                    ("khowarib", "Khowarib"),
                    ("omukutu", "Omukutu"),
                    ("otjondumbu", "Otjondumbu"),
                    ("okaturua", "Okaturua"),
                    ("otjatjondjira", "Otjatjondjira"),
                ],
                default="warmquelle",
                max_length=50,
            ),
        ),
    ]
