# Generated by Django 5.1.6 on 2025-04-07 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_member_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='company',
        ),
    ]
