# Generated by Django 5.1.6 on 2025-04-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='employment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
