version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: anabeb-image:latest
    container_name: anabeb-container
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
